#!/usr/bin/env node
// Instant Audit. Usage: audit.mjs <url> [--json|--md]
const args=process.argv.slice(2),u=args.find(a=>!a.startsWith('--')),asJson=args.includes('--json'),asMd=args.includes('--md');
if(!u){console.error('Usage: audit.mjs <url> [--json|--md]');process.exit(1);}
const target=(/^https?:\/\//i.test(u)?u:'https://'+u).replace(/\/+$/,'');const KEY=process.env.PAGESPEED_API_KEY||'';
async function hdr(url){const w=['strict-transport-security','content-security-policy','x-content-type-options','x-frame-options','referrer-policy'];const r={https:url.startsWith('https://'),reachable:false,missing:[]};try{const res=await fetch(url,{redirect:'follow',signal:AbortSignal.timeout(12000)});r.reachable=true;for(const h of w)if(!res.headers.get(h))r.missing.push(h);}catch(e){r.error=String(e.message||e);}return r;}
async function psi(url,s){const q=new URLSearchParams();q.set('url',url);q.set('strategy',s);['performance','accessibility','best-practices','seo'].forEach(c=>q.append('category',c));if(KEY)q.set('key',KEY);const res=await fetch('https://www.googleapis.com/pagespeedonline/v5/runPagespeed?'+q,{signal:AbortSignal.timeout(60000)});if(!res.ok)throw new Error('PSI '+res.status);const cat=((await res.json()).lighthouseResult||{}).categories||{};const sc=k=>cat[k]&&typeof cat[k].score==='number'?Math.round(cat[k].score*100):null;return{performance:sc('performance'),accessibility:sc('accessibility'),bestPractices:sc('best-practices'),seo:sc('seo')};}
function score({mobile,desktop,headers}){const n=v=>typeof v==='number'?v:0;const mp=n(mobile?.performance),seo=n(mobile?.seo??desktop?.seo),a=n(mobile?.accessibility),bp=n(mobile?.bestPractices);const hs=headers?.reachable?Math.round(((5-(headers.missing?.length??5))/5)*100):0,ht=headers?.https?100:0;return Math.round(mp*.3+seo*.2+hs*.2+ht*.1+a*.1+bp*.1);}
const grade=s=>s>=90?'A':s>=80?'B':s>=65?'C':s>=50?'D':'F';
(async()=>{const[headers,mobile,desktop]=await Promise.all([hdr(target),psi(target,'mobile').catch(e=>({error:e.message})),psi(target,'desktop').catch(e=>({error:e.message}))]);const s=score({mobile,desktop,headers});const rep={url:target,siteWrightScore:s,grade:grade(s),https:headers.https,securityHeadersMissing:headers.missing||[],mobile,desktop};
if(asJson){console.log(JSON.stringify(rep,null,2));return;}
if(asMd){console.log(`# Audit — ${target}\n\n**Score: ${s}/100 (${rep.grade})**\n- HTTPS: ${headers.https?'✅':'❌'}\n- Missing headers: ${(headers.missing||[]).join(', ')||'none'}\n`);return;}
console.log(`\n🔍 Audit — ${target}\n   Score: ${s}/100 (${rep.grade}) · HTTPS: ${headers.https?'✅':'❌'}`);if(mobile&&!mobile.error)console.log(`   Mobile perf ${mobile.performance} · SEO ${mobile.seo}`);if(!KEY)console.log('   ⚠️  no PAGESPEED_API_KEY');console.log('');})().catch(e=>{console.error('Audit failed:',e.message);process.exit(1);});
