#!/usr/bin/env node
// Lead Finder. Usage: find-leads.mjs "<niche>" "<city>" [--audit --csv|--json --max N]
import '../../../env.mjs';
import {spawnSync} from 'node:child_process';import {resolve,dirname} from 'node:path';import {fileURLToPath} from 'node:url';
const A=resolve(dirname(fileURLToPath(import.meta.url)),'../../audit/src/audit.mjs');
const args=process.argv.slice(2),p=args.filter(a=>!a.startsWith('--')),niche=p[0],loc=p[1],doAudit=args.includes('--audit'),asCsv=args.includes('--csv'),asJson=args.includes('--json'),mi=args.indexOf('--max'),MAX=mi>=0?(parseInt(args[mi+1])||20):20;
if(!niche||!loc){console.error('Usage: find-leads.mjs "<niche>" "<city>" [--audit --csv|--json --max N]');process.exit(1);}
const KEY=process.env.GOOGLE_PLACES_API_KEY||'';if(!KEY){console.error('❌ GOOGLE_PLACES_API_KEY not set (.env)');process.exit(1);}
async function search(q){const fm=['places.displayName','places.formattedAddress','places.nationalPhoneNumber','places.websiteUri','places.rating','places.userRatingCount','places.primaryType','places.businessStatus'].join(',');const res=await fetch('https://places.googleapis.com/v1/places:searchText',{method:'POST',headers:{'Content-Type':'application/json','X-Goog-Api-Key':KEY,'X-Goog-FieldMask':fm},body:JSON.stringify({textQuery:q,maxResultCount:Math.min(MAX,20)}),signal:AbortSignal.timeout(20000)});if(!res.ok)throw new Error('Places '+res.status);return (await res.json()).places||[];}
function audit(url){const r=spawnSync('node',[A,url,'--json'],{encoding:'utf8',timeout:90000});if(r.status!==0||!r.stdout)return null;try{return JSON.parse(r.stdout);}catch{return null;}}
function sl(p,a){const has=!!p.websiteUri,rev=p.userRatingCount||0;let s=0;const why=[];if(!has){s+=40;why.push('No website');}else if(a&&typeof a.siteWrightScore==='number'){s+=Math.round((100-a.siteWrightScore)*.6);if(!a.https){s+=10;why.push('No HTTPS');}if(a.siteWrightScore<50)why.push(`Site ${a.siteWrightScore}/100`);}else if(has){s+=10;why.push('Has site');}if(rev>=100){s+=20;why.push(rev+' reviews');}else if(rev>=25){s+=12;why.push(rev+' reviews');}else if(rev>=5)s+=6;if(p.rating>=4)s+=5;const os=Math.min(s,100);return{opportunityScore:os,priority:os>=55?'HOT':os>=35?'WARM':'COOL',why};}
(async()=>{const q=`${niche} in ${loc}`;const places=(await search(q)).filter(p=>!p.businessStatus||p.businessStatus==='OPERATIONAL').slice(0,MAX);const leads=[];for(const p of places){let a=null;if(doAudit&&p.websiteUri)a=audit(p.websiteUri);const sc=sl(p,a);leads.push({name:p.displayName?.text||'',phone:p.nationalPhoneNumber||'',address:p.formattedAddress||'',website:p.websiteUri||'',hasWebsite:!!p.websiteUri,rating:p.rating??null,reviews:p.userRatingCount??0,type:p.primaryType||niche,siteScore:a?a.siteWrightScore:null,...sc});}leads.sort((a,b)=>b.opportunityScore-a.opportunityScore);
if(asJson){console.log(JSON.stringify({query:q,count:leads.length,leads},null,2));return;}
if(asCsv){const e=s=>`"${String(s??'').replace(/"/g,'""')}"`;console.log('priority,score,name,phone,address,website,siteScore,rating,reviews,type,why');leads.forEach(l=>console.log([l.priority,l.opportunityScore,e(l.name),e(l.phone),e(l.address),e(l.website),l.siteScore??'',l.rating??'',l.reviews,e(l.type),e(l.why.join('; '))].join(',')));return;}
console.log(`\n📍 "${q}" → ${leads.length}\n`);leads.forEach((l,i)=>{const t=l.priority==='HOT'?'🔥 HOT ':l.priority==='WARM'?'☀️  WARM':'❄️  COOL';console.log(`${String(i+1).padStart(2)}. [${t}] ${l.name} (${l.opportunityScore}/100)\n     ${l.phone||'no phone'} · ${l.hasWebsite?l.website:'NO WEBSITE'} · ⭐${l.rating??'—'} (${l.reviews})\n     ${l.why.join(' · ')}\n`);});console.log('Tip: run /find-opportunities on each site to pitch specific weak points.');})().catch(e=>{console.error('failed:',e.message);process.exit(1);});
