#!/usr/bin/env node
// Site Capture. Usage: capture.mjs <url-or-html> [--slug X] [--json]  → parity/<slug>/{baseline.json,baseline.md,brand.seed.json}
import {readFileSync,existsSync,mkdirSync,writeFileSync} from 'node:fs';import {resolve} from 'node:path';
const args=process.argv.slice(2),target=args.find(a=>!a.startsWith('--')),asJson=args.includes('--json'),slugOpt=(i=>i>=0?args[i+1]:null)(args.indexOf('--slug'));
if(!target){console.error('Usage: capture.mjs <url-or-html> [--slug X] [--json]');process.exit(1);}
const slugify=s=>String(s||'site').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,60);
async function load(t){if(/^https?:\/\//i.test(t)){const res=await fetch(t,{redirect:'follow',signal:AbortSignal.timeout(20000),headers:{'User-Agent':'SiteWright/1.0'}});return{html:await res.text(),base:new URL(t)};}if(!existsSync(t)){console.error('Not found');process.exit(1);}return{html:readFileSync(t,'utf8'),base:null};}
async function css(html,base){if(!base)return'';const hrefs=[...html.matchAll(/<link[^>]+rel\s*=\s*["']stylesheet["'][^>]*>/gi)].map(m=>(m[0].match(/href\s*=\s*["']([^"']+)["']/i)||[])[1]).filter(Boolean).slice(0,4);let c='';for(const h of hrefs){try{const res=await fetch(new URL(h,base).href,{signal:AbortSignal.timeout(10000)});if(res.ok)c+='\n'+(await res.text()).slice(0,200000);}catch{}}return c;}
const strip=s=>(s||'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim(),btw=(h,t)=>{const m=h.match(new RegExp(`<${t}\\b[^>]*>([\\s\\S]*?)</${t}>`,'i'));return m?m[1]:null;},allB=(h,t)=>[...h.matchAll(new RegExp(`<${t}\\b[^>]*>([\\s\\S]*?)</${t}>`,'gi'))].map(m=>strip(m[1])).filter(Boolean),meta=(h,n)=>{const m=h.match(new RegExp(`<meta[^>]+(?:name|property)\\s*=\\s*["']${n}["'][^>]*content\\s*=\\s*["']([^"']+)["']`,'i'));return m?m[1]:null;};
function colors(t){const hx={};for(const m of t.matchAll(/#([0-9a-fA-F]{6}|[0-9a-fA-F]{3})\b/g)){let h=m[1].length===3?m[1].split('').map(c=>c+c).join(''):m[1];h='#'+h.toLowerCase();hx[h]=(hx[h]||0)+1;}const r=Object.entries(hx).sort((a,b)=>b[1]-a[1]).map(([h])=>h),neut=h=>h==='#ffffff'||h==='#000000',viv=r.filter(h=>!neut(h));return{all:r.slice(0,12),primary:viv[0]||r[0]||'#1d4ed8',accent:viv[1]||viv[0]||'#f59e0b',background:r.find(h=>/^#(f|e)/.test(h))||'#ffffff',text:r.find(h=>/^#(0|1|2|3)/.test(h))||'#0f172a'};}
function fonts(t){const f=new Set();for(const m of t.matchAll(/font-family\s*:\s*([^;{}]+)/gi)){const x=m[1].split(',')[0].replace(/["']/g,'').trim();if(x&&!/^(inherit|initial|var\()/i.test(x))f.add(x);}for(const m of t.matchAll(/fonts\.googleapis\.com\/css2?\?family=([^"'&]+)/gi))f.add(decodeURIComponent(m[1]).split(':')[0].replace(/\+/g,' '));return[...f].slice(0,6);}
function detect(html){const h=html.toLowerCase(),f=new Set(),has=(...k)=>k.some(x=>h.includes(x));if(/<form\b/i.test(html))f.add('contact-form');if(/href\s*=\s*["']tel:/i.test(html))f.add('click-to-call');if(has('maps.google','google.com/maps'))f.add('map');if(has('instagram.com','facebook.com','youtube.com','tiktok.com'))f.add('social');if(has('toasttab','chownow','gloriafood','ontabee','order online','/order'))f.add('online-ordering');if(has('opentable','resy','exploretock','reservation'))f.add('reservations');if(has('calendly','simplybook','acuity','appointments','book now','schedule'))f.add('booking');if(has('menu')&&(has('$')||/class\s*=\s*["'][^"']*menu/i.test(html)))f.add('menu');if(has('snipcart','add to cart','/cart','shop now'))f.add('store');if(has('stripe','checkout','buy now','paypal','paddle'))f.add('payments');if(has('mailchimp','brevo','newsletter','subscribe'))f.add('newsletter');if(has('wa.me','whatsapp'))f.add('whatsapp');if(has('tawk.to','crisp.chat','intercom'))f.add('live-chat');if((html.match(/<img\b/gi)||[]).length>=6||has('gallery','lightbox'))f.add('gallery');if(has('faq','frequently asked'))f.add('faq');if(has('review','testimonial','★','⭐'))f.add('reviews');const prov={};const dp=(m)=>{for(const[k,v]of Object.entries(m))if(h.includes(k))return v;return null;};if(f.has('online-ordering'))prov['online-ordering']=dp({toasttab:'Toast',chownow:'ChowNow',gloriafood:'GloriaFood',squareup:'Square'});if(f.has('reservations'))prov.reservations=dp({opentable:'OpenTable',resy:'Resy',exploretock:'Tock'});if(f.has('booking'))prov.booking=dp({calendly:'Calendly',simplybook:'SimplyBook.me',acuity:'Acuity'});return{features:[...f],providers:prov};}
function contact(html){const t=strip(html);return{phone:(t.match(/(\+?\d[\d\s().-]{7,}\d)/)||[])[0]||(html.match(/tel:([+\d]+)/i)||[])[1]||null,email:(html.match(/mailto:([^"'>\s]+)/i)||[])[1]||(t.match(/[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}/i)||[])[0]||null,address:(t.match(/\d{1,5}\s+[A-Za-z0-9.\s]{3,40}(?:St|Street|Ave|Avenue|Blvd|Rd|Road|Dr|Drive|Ln|Way|Ct)\b[^,]*,?\s*[A-Za-z\s]*,?\s*[A-Z]{2}\s*\d{5}?/)||[])[0]||null};}
function nav(html,base){const links=[...html.matchAll(/<a\b[^>]*href\s*=\s*["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)],internal=[];for(const m of links){const href=m[1],label=strip(m[2]);if(!label||label.length>30)continue;if(/^(https?:)?\/\//i.test(href)){if(base&&href.includes(base.host))internal.push({href,label});}else internal.push({href,label});}const seen=new Set();return internal.filter(l=>{const k=l.label.toLowerCase();if(seen.has(k))return false;seen.add(k);return true;}).slice(0,15);}
(async()=>{const{html,base}=await load(target),cssText=await css(html,base),style=cssText+'\n'+html,c=colors(style),ft=fonts(style),title=strip(btw(html,'title'))||'',name=meta(html,'og:site_name')||allB(html,'h1')[0]||title.split(/[|\-–—]/)[0].trim()||'Business',desc=meta(html,'description')||meta(html,'og:description')||'',logo=(html.match(/<img[^>]+src\s*=\s*["']([^"']*logo[^"']*)["']/i)||[])[1]||null,{features,providers}=detect(html),ct=contact(html),pages=nav(html,base);
const slug=slugify(slugOpt||name);const baseline={source:target,capturedAt:new Date().toISOString(),slug,business:{name,description:desc},style:{colors:{primary:c.primary,accent:c.accent,background:c.background,text:c.text},palette:c.all,fonts:ft,logo},structure:{title,pages,headings:{h1:allB(html,'h1').slice(0,5),h2:allB(html,'h2').slice(0,12)}},functionality:{features,providers},contact:ct};
const dir=resolve(process.cwd(),'parity',slug);mkdirSync(dir,{recursive:true});writeFileSync(resolve(dir,'baseline.json'),JSON.stringify(baseline,null,2));
const seed={businessName:name,tagline:desc.slice(0,80),brand:{colors:{primary:c.primary,secondary:c.text,accent:c.accent},font:{heading:ft[0]||'Inter',body:ft[1]||ft[0]||'Inter'},logo:'assets/logo.svg'},contact:{phone:ct.phone||'',email:ct.email||'',address:ct.address||'',hours:'Mon-Fri 9-5'},features:{contactForm:features.includes('contact-form'),booking:features.includes('booking'),payments:features.includes('payments'),store:features.includes('store')},addons:features};writeFileSync(resolve(dir,'brand.seed.json'),JSON.stringify(seed,null,2));
const md=`# Parity Brief — ${name}\n_Captured from ${target} on ${new Date(baseline.capturedAt).toLocaleString()}_\n\n## Goal\nRebuild cheaper, keep the visual style, preserve ALL functionality, improve quality.\n\n## Visual style\n- Primary ${c.primary} · Accent ${c.accent} · BG ${c.background} · Text ${c.text}\n- Fonts: ${ft.join(', ')||'—'} · Logo: ${logo||'(ask client)'}\n\n## Functionality to preserve\n${features.length?features.map(f=>`- **${f}**${providers[f]?` (was: ${providers[f]})`:''}`).join('\n'):'- (none detected)'}\n${ct.phone?`- Phone: ${ct.phone}`:''}${ct.email?`\n- Email: ${ct.email}`:''}\n\n## Pages\n${pages.length?pages.map(p=>`- ${p.label} (${p.href})`).join('\n'):'- (none)'}\n\n## Use\n1. /new-client with brand.seed.json (matches the look). 2. /add-feature each item. 3. build → parity-check.\n`;writeFileSync(resolve(dir,'baseline.md'),md);
if(asJson){console.log(JSON.stringify(baseline,null,2));return;}
console.log(`\n📸 Captured "${name}" → parity/${slug}/`);console.log(`   Style: primary ${c.primary} · accent ${c.accent} · fonts ${ft.slice(0,2).join(', ')||'—'}`);console.log(`   Preserve: ${features.join(', ')||'(none)'}`);console.log(`   Files: baseline.json · baseline.md · brand.seed.json\n   Next: /new-client (use brand.seed.json) → /add-feature each → build → parity-check ${slug} <new>\n`);})().catch(e=>{console.error('Capture failed:',e.message);process.exit(1);});
