#!/usr/bin/env node
// Parity Check. Usage: parity-check.mjs <slug|baseline.json> <new-url-or-html> [--json]. Exit 1 if regression.
import {readFileSync,existsSync} from 'node:fs';import {resolve} from 'node:path';
const args=process.argv.slice(2),bl=args.filter(a=>!a.startsWith('--'))[0],nw=args.filter(a=>!a.startsWith('--'))[1],asJson=args.includes('--json');
if(!bl||!nw){console.error('Usage: parity-check.mjs <slug|baseline.json> <new-url-or-html> [--json]');process.exit(2);}
let bp=bl;if(!existsSync(bp))bp=resolve(process.cwd(),'parity',bl,'baseline.json');if(!existsSync(bp)){console.error(`Baseline not found. Run capture first.`);process.exit(2);}
const B=JSON.parse(readFileSync(bp,'utf8'));
async function load(t){if(/^https?:\/\//i.test(t)){const res=await fetch(t,{redirect:'follow',signal:AbortSignal.timeout(20000)});return await res.text();}if(!existsSync(t)){console.error('New site not found');process.exit(2);}return readFileSync(t,'utf8');}
function detect(html){const h=html.toLowerCase(),f=new Set(),has=(...k)=>k.some(x=>h.includes(x));if(/<form\b/i.test(html))f.add('contact-form');if(/href\s*=\s*["']tel:/i.test(html))f.add('click-to-call');if(has('maps.google','google.com/maps'))f.add('map');if(has('instagram.com','facebook.com','youtube.com','tiktok.com'))f.add('social');if(has('toasttab','chownow','gloriafood','ontabee','order online','/order'))f.add('online-ordering');if(has('opentable','resy','exploretock','reservation'))f.add('reservations');if(has('calendly','simplybook','acuity','appointments','book now','schedule'))f.add('booking');if(has('menu')&&(has('$')||/class\s*=\s*["'][^"']*menu/i.test(html)))f.add('menu');if(has('snipcart','add to cart','/cart','shop now'))f.add('store');if(has('stripe','checkout','buy now','paypal','paddle'))f.add('payments');if(has('mailchimp','brevo','newsletter','subscribe'))f.add('newsletter');if(has('wa.me','whatsapp'))f.add('whatsapp');if(has('tawk.to','crisp.chat','intercom'))f.add('live-chat');if((html.match(/<img\b/gi)||[]).length>=6||has('gallery','lightbox'))f.add('gallery');if(has('faq','frequently asked'))f.add('faq');if(has('review','testimonial','★','⭐'))f.add('reviews');return f;}
function cp(html,hex){if(!hex)return false;const h=html.toLowerCase();if(h.includes(hex.toLowerCase()))return true;const n=hex.replace('#','');if(n.length!==6)return false;const r=parseInt(n.slice(0,2),16),g=parseInt(n.slice(2,4),16),b=parseInt(n.slice(4,6),16);return h.includes(`rgb(${r}, ${g}, ${b})`)||h.includes(`rgb(${r},${g},${b})`);}
(async()=>{const html=await load(nw),nf=detect(html),of=new Set(B.functionality?.features||[]),nlow=html.toLowerCase();const res={regressions:[],preserved:[],improvements:[],style:[],contact:[],pages:[]};
for(const f of of)nf.has(f)?res.preserved.push(f):res.regressions.push(f);for(const f of nf)if(!of.has(f))res.improvements.push(f);
const c=B.style?.colors||{};res.style.push({item:`primary ${c.primary||'—'}`,ok:cp(html,c.primary)});res.style.push({item:`accent ${c.accent||'—'}`,ok:cp(html,c.accent)});const ft=B.style?.fonts||[];if(ft.length)res.style.push({item:`font "${ft[0]}"`,ok:nlow.includes(ft[0].toLowerCase())});
const ct=B.contact||{};if(ct.phone)res.contact.push({item:'phone',ok:nlow.replace(/[^0-9]/g,'').includes(ct.phone.replace(/[^0-9]/g,''))});if(ct.email)res.contact.push({item:'email',ok:nlow.includes(ct.email.toLowerCase())});
for(const p of (B.structure?.pages||[])){const l=p.label.toLowerCase();if(['home','skip to content','menu'].includes(l))continue;res.pages.push({item:p.label,ok:nlow.includes(l)});}
const pass=res.regressions.length===0;
if(asJson){console.log(JSON.stringify({slug:B.slug,pass,results:res},null,2));process.exit(pass?0:1);}
console.log(`\n🔀 Parity Check — ${B.business?.name||B.slug}\n   old: ${B.source}\n   new: ${nw}\n\n  Functionality:`);res.preserved.forEach(f=>console.log(`    ✅ preserved: ${f}`));res.regressions.forEach(f=>console.log(`    ❌ MISSING (regression): ${f} — add it before launch.`));res.improvements.forEach(f=>console.log(`    ✨ added: ${f}`));
console.log(`\n  Visual style:`);res.style.forEach(s=>console.log(`    ${s.ok?'✅':'⚠️ '} ${s.item}${s.ok?'':' — match for consistency.'}`));
if(res.contact.length){console.log(`\n  Contact retained:`);res.contact.forEach(s=>console.log(`    ${s.ok?'✅':'❌'} ${s.item}`));}
if(res.pages.length){console.log(`\n  Pages:`);res.pages.forEach(s=>console.log(`    ${s.ok?'✅':'⚠️ '} ${s.item}`));}
console.log(`\n  Summary: ${res.preserved.length} preserved · ${res.improvements.length} added · ${res.regressions.length} regressions`);
if(!pass)console.log(`  ❌ ${res.regressions.length} old feature(s) missing — hand to qa-debugger.`);else console.log(`  🎉 Full parity — nothing lost, ${res.improvements.length} improvement(s) added. Cheaper AND better.`);console.log('');process.exit(pass?0:1);})().catch(e=>{console.error('failed:',e.message);process.exit(2);});
